### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by DeyvidKochanov-TomTom** [johnwlambert/tbv#1]
Hi,
thank you for the code and the interesting paper! Really amazing work on a very relevant problem! Will the data be released soon? We are really eager to run some experiments on it!

**Comment by johnwlambert** [comment]
Hi @DeyvidKochanov-TomTom, thanks for your interest in our work. Yes -- we are planning to release the dataset around the time of the NeurIPS 2021 conference. If you'd like to receive a note immediately when the dataset is released, feel free to subscribe as a watcher of this repo and we'll post more updates here.

**Comment by DeyvidKochanov-TomTom** [comment]
Thanks, I have subscribed!

**Comment by DeyvidKochanov-TomTom** [comment]
Hi,
anything new about the dataset?

**Comment by johnwlambert** [comment]
Hi @DeyvidKochanov-TomTom, thanks for your patience here. It is a massive release so we are still in the final stages. I'm hoping this next week or the week after we can put the files online.

**Comment by johnwlambert** [comment]
Hi @DeyvidKochanov-TomTom @ZiningWang @fatemehkariminejadasl-tomtom, the _Trust but Verify Dataset_ is now available for download. You can find more information at the following links:

- [TbV Dataset Readme](https://github.com/argoai/av2-api/blob/main/src/av2/datasets/tbv/README.md)
- [Download Instructions](https://github.com/argoai/av2-api/blob/main/src/av2/datasets/tbv/README.md#downloading-tbv)
- [Download Links](https://www.argoverse.org/av2.html#download-link)

Please feel free to open new issues if you have additional questions or comments. Enjoy!
