### ISSUE TITLE
question

### ISSUE THREAD

**Issue by laozheng1** [johnwlambert/tbv#2]
Thank you for your code. The code is great. At present, I am doing my graduation project based on your paper   trust, but verify: cross modality fusion For HD map change detection   as a reference.  And I'm running the code you uploaded on GitHub. When I ran Rendering Training Data I found a Python file named data_Splits missing from the tbv folder. I don't know if it's my fault. I would appreciate it if you could help answer the question.

**Comment by SONGLEI-arch** [comment]
Thank you for your code. I also encountered a similar problem when studying your paper. Some files such as data_ splits seem to be missing. I would appreciate it if you could help me.

**Comment by johnwlambert** [comment]
Hi @laozheng1 and @SONGLEI-arch, thanks for your interest in our work. The codebase uses the Trust but Verify (TbV) dataset. We are finishing up the TbV Dataset release preparations and the data will be released shortly. The data splits will also be distributed at that time.

**Comment by HoudaAtr** [comment]
Hi @johnwlambert , thank you first for sharing this amazing work! I'm trying to render training data using you code, however, I find that data_splits and histogram_matching files are missing, do you have any idea when they will be released?

**Comment by johnwlambert** [comment]
Hi @HoudaAtr, thanks for your interest. All of the val + test log_ids are included in the scene clustering here:
https://github.com/argoai/av2-api/pull/26/files

Other logs are from the train split. I'll release the official train/val/test splits in the coming few days. I'll push a fix for the `histogram_matching.py` file -- thanks for the heads up!

**Comment by johnwlambert** [comment]
Official TbV data splits can be found [here](https://github.com/johnwlambert/tbv/blob/main/tbv/splits.py). Please re-open the issue if you run into other problems.

**Comment by HoudaAtr** [comment]
@johnwlambert  thank you for uploading data splits. Could you please upload histogram_matching.py file as well?

**Comment by johnwlambert** [comment]
@HoudaAtr That file won't be released -- all of the BEV configs for the released pretrained models have `use_histogram_matching: False`, so that functionality is not needed. The `import` statement is wrapped in `try / except` so the codebase is not affected. Using histogram matching didn't improve quantitative results in experiments.
