### ISSUE TITLE
Missing train and test scripts

### ISSUE THREAD

**Issue by LianneTjin** [johnwlambert/tbv#6]
Hi @johnwlambert first of all I'd like to thank you for sharing your code and data. This is really a big step forward in the field of HD map change detection! I've managed to render the ego-view training data and wanted to start on training one of the models you've included but noticed that the train and test files you're referring to in the README are missing in the scripts folder. So I was wondering whether those are going to be released and if so do you happen to be able to give an indication of when?

**Comment by johnwlambert** [comment]
Hi @LianneTjin, thanks for your interest in our work. That code was added to complete the code release here: https://github.com/johnwlambert/tbv/pull/7
